[package]
name = "boolish-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boolish-code = { path = "../boolish-code" }

[lib]
proc-macro = true
